### ISSUE TITLE
Error with 'whenever' rake task redirecting output to log file

### ISSUE THREAD

**Issue by spovich** [jfelchner/ruby-progressbar#108]
I'm having an issue with `ruby-progressbar` when running a rake task via cron (using the `whenever` ruby gem which adds jobs to cron).  The resulting cron entry looks like this:

```
00 09 * * * /bin/bash -l -c 'cd /path/to/foo && RAILS_ENV=production bundle exec rake my_task --silent >> log/test.log 2>&1'
```
This produces an error with progress bar:
```
NoMethodError: undefined method `+' for nil:NilClass
/var/deploy/web_head/shared/bundle/ruby/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:51:in `print_and_flush'
/var/deploy/web_head/shared/bundle/ruby/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:46:in `block in refresh'
/var/deploy/web_head/shared/bundle/ruby/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/throttle.rb:22:in `choke'
/var/deploy/web_head/shared/bundle/ruby/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:43:in `refresh'
/var/deploy/web_head/shared/bundle/ruby/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb:39:in `with_refresh'
/var/deploy/web_head/shared/bundle/ruby/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb:155:in `update_progress'
/var/deploy/web_head/shared/bundle/ruby/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb:103:in `total='
```

If I remove the redirecting of `STDOUT` and `STDERR` to the log file, the rake task will run to completion:
```
00 09 * * * /bin/bash -l -c 'cd /path/to/foo && RAILS_ENV=production bundle exec rake my_task --silent'
```

I tried a few variations (just redirecting `STDOUT` and just redirecting `STDERR`) but those failed as well.

**Comment by jfelchner** [comment]
@spovich great.  Thanks for the report.  How about a gist with some sample files to reproduce the problem?

**Comment by spovich** [comment]
Well, I've tried to reproduce the problem with a simplified test case and can't do it.  So, it must be something buried in the setup we have.  Thanks!
