### ISSUE TITLE
%a, %e, %E behavior failing or erroring with Rails 5.2

### ISSUE THREAD

**Issue by bbugh** [jfelchner/ruby-progressbar#150]
## Current Behavior

There seems to be an issue with Progressbar time formatting with Rails 5.2.

1. Using `%a` never updates the `Time:` 
2. Using `%e` and `%E` crashes.

I listed these both together as they seem to be related.

### Steps to Reproduce

**With %a**
1. Rails 5.2
2. Try ProgressBar with  `ProgressBar.create(format: "%t (%c/%C): |%w| %a")`
3. The Time never updates (just says `Time: --:--:--` forever).

**With %e/%E**
1. Rails 5.2
2. Try ProgressBar with `ProgressBar.create(format: "%t (%c/%C): |%w| %e")`
3. Ruby dies, it's a total catastrophe, there's code everywhere

<details>
<summary>Stack trace details</summary>

```
TypeError: can't convert nil into an exact number
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/core_ext/time/calculations.rb:275:in `-'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/core_ext/time/calculations.rb:275:in `minus_with_duration'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/activesupport-5.2.0/lib/active_support/core_ext/time/calculations.rb:286:in `minus_with_coercion'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/timer.rb:54:in `elapsed_seconds'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/components/time.rb:94:in `estimated_seconds_remaining'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/components/time.rb:66:in `estimated'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/components/time.rb:23:in `estimated_with_label'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/components/time.rb:88:in `estimated_with_elapsed_fallback'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/components/time.rb:41:in `estimated_with_unknown_oob'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/format/molecule.rb:55:in `lookup_value'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/format/formatter.rb:8:in `block in process'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/format/formatter.rb:7:in `each'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/format/formatter.rb:7:in `process'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/base.rb:123:in `to_s'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/outputs/tty.rb:16:in `bar_update_string'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/output.rb:64:in `print_and_flush'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/output.rb:51:in `block in refresh'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/throttle.rb:22:in `choke'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/output.rb:48:in `refresh'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/output.rb:44:in `with_refresh'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/base.rb:177:in `update_progress'
/Users/bbugh/.rvm/gems/ruby-2.5.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/base.rb:93:in `increment'
```
</details>

## Expected Behavior

The timing-based settings should work as described in the documentation. %a shows the elapsed time and %e/%E show the estimated time.

## Environment

- OS: Mac
- OS Version: 10.12.6
- Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]
- Rails version: Rails 5.2.0

**Comment by jfelchner** [comment]
This is why monkeypatching core classes sucks.

**Comment by jfelchner** [comment]
@bbugh @cryptomeme I just tried this with Rails 5.2.3 and did not get the behavior you described above.

```
rails new pbtest
echo "gem 'ruby-progressbar'" >> Gemfile
bundle install
rails console
pb = ProgressBar.create(format: "%t (%c/%C): |%w| %e")
50.times { pb.increment; sleep 0.1 }
```

Works as expected.

Additionally:

```
require 'active_support/testing/time_helpers'
include ::ActiveSupport::Testing::TimeHelpers

travel_to(1.day.ago) do
  pb = ProgressBar.create(format: "%t (%c/%C): |%w| %e")
  50.times { pb.increment; sleep 0.1 }
end
```

does as well.

However:

```
require 'active_support/testing/time_helpers'
include ::ActiveSupport::Testing::TimeHelpers

pb = ProgressBar.create(format: "%t (%c/%C): |%w| %e")

travel_to(1.day.ago) do
  50.times { pb.increment; sleep 0.1 }
end
```

Does not, which is understandable because the progress bar is created _outside_ of the stubbing and therefore when the bar is created, we don't know that it needs to work around time mocking.  And because checking that on every bar increment would be performance intensive, we assume that the conditions the bar was created in is what we need to use for the remainder of the bar.

Now, if you'd really like to create the bar outside of the block, you can do something like:

```
require 'active_support/testing/time_helpers'
include ::ActiveSupport::Testing::TimeHelpers

pb = ProgressBar.create(format: "%t (%c/%C): |%w| %e", autostart: false)

travel_to(1.day.ago) do
  pb.start
  50.times { pb.increment; sleep 0.1 }
end
```

Because the bar doesn't start its timer until it's inside the block, after we've mocked `Time`, then everything works as expected.

Hope this helps!

**Comment by jfelchner** [comment]
Also if I'm missing something, do me a favor and send me a more robust reproduction via a fresh Rails 5.2 app and I'll take another look.
