### ISSUE TITLE
Segfault when profiling

### ISSUE THREAD

**Issue by erwanlr** [jfelchner/ruby-progressbar#153]
I've been profiling my gems with Stackprof, however ruby-progressbar trigger a segfault.

Code to reproduce:
```ruby
require 'stackprof'
require 'ruby-progressbar'

StackProf.run(mode: :object, out: '/tmp/stackprof-object.dump') do
  bar = ProgressBar.create
end
```

Trace:
```
$ ruby ruby_progressbar_segfault.rb 
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/time.rb:21: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin18]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:                    
     * ~/Library/Logs/DiagnosticReports                                     
     * /Library/Logs/DiagnosticReports                                      
   for more details.                                                        
Don't forget to include the above Crash Report log file in bug reports.     

-- Control frame information -----------------------------------------------
c:0014 p:---- s:0058 e:000057 IFUNC 
c:0013 p:---- s:0055 e:000054 CFUNC  :each
c:0012 p:---- s:0052 e:000051 CFUNC  :find
c:0011 p:0025 s:0048 e:000047 METHOD /Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/time.rb:21
c:0010 p:0008 s:0044 e:000042 METHOD /Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/time.rb:16
c:0009 p:0037 s:0039 e:000037 METHOD /Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/timer.rb:13
c:0008 p:0011 s:0034 e:000033 METHOD /Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/base.rb:40
c:0007 p:0250 s:0029 e:000028 METHOD /Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/base.rb:36 [FINISH]
c:0006 p:---- s:0024 e:000023 CFUNC  :new
c:0005 p:0016 s:0020 e:000019 METHOD /Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar.rb:16
c:0004 p:0011 s:0015 e:000014 BLOCK  ruby_progressbar_segfault.rb:6 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :run
c:0002 p:0029 s:0006 e:000005 EVAL   ruby_progressbar_segfault.rb:4 [FINISH]
c:0001 p:0000 s:0003 E:002320 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
ruby_progressbar_segfault.rb:4:in `<main>'
ruby_progressbar_segfault.rb:4:in `run'
ruby_progressbar_segfault.rb:6:in `block in <main>'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar.rb:16:in `create'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar.rb:16:in `new'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/base.rb:36:in `initialize'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/base.rb:40:in `start'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/timer.rb:13:in `start'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/time.rb:16:in `now'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/time.rb:21:in `unmocked_time_method'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/time.rb:21:in `find'
/Users/user/.rvm/gems/ruby-2.6.1/gems/ruby-progressbar-1.10.0/lib/ruby-progressbar/time.rb:21:in `each'
```

**Comment by jfelchner** [comment]
This segfault is a bug in stackprof and should be reported to them.
